# Generated by Django 5.1.1 on 2024-09-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare', '0002_profile_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janNotes', models.TextField()),
                ('febNotes', models.TextField()),
                ('marNotes', models.TextField()),
                ('aprNotes', models.TextField()),
                ('mayNotes', models.TextField()),
                ('junNotes', models.TextField()),
                ('julNotes', models.TextField()),
                ('augNotes', models.TextField()),
                ('sepNotes', models.TextField()),
                ('octNotes', models.TextField()),
                ('novNotes', models.TextField()),
                ('decNotes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='months',
            field=models.ManyToManyField(blank=True, to='skinCare.monthoverview'),
        ),
    ]
