# Generated by Django 5.1.1 on 2024-09-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare', '0003_monthoverview_profile_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aprNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='augNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='decNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='febNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='janNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='julNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='junNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='marNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='mayNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='novNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='octNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='sepNotes',
            field=models.TextField(default=''),
        ),
    ]
