# Generated by Django 5.1.1 on 2024-09-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare', '0004_profile_aprnotes_profile_augnotes_profile_decnotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='months',
        ),
    ]
