# Generated by Django 5.1.1 on 2024-09-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare', '0005_remove_profile_months'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aprNotes',
            new_name='aprilNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='augNotes',
            new_name='augustNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='decNotes',
            new_name='decemberNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='febNotes',
            new_name='februaryNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='janNotes',
            new_name='januaryNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='julNotes',
            new_name='julyNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='junNotes',
            new_name='juneNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='marNotes',
            new_name='marchNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='novNotes',
            new_name='novemberNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='octNotes',
            new_name='octoberNotes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sepNotes',
            new_name='septemberNotes',
        ),
    ]
