# Generated by Django 5.1.1 on 2024-09-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare', '0006_rename_aprnotes_profile_aprilnotes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthOverview',
        ),
    ]
