# Generated by Django 5.1.1 on 2024-09-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare', '0007_delete_monthoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
